version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: notifier-service-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - notifier-network

  redis:
    image: redis:7
    container_name: notifier-service-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - notifier-network

volumes:
  mongo_data:
  redis_data:

networks:
  notifier-network:
    driver: bridge